#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : idna-ssl
Version  : 1.1.0
Release  : 9
URL      : https://files.pythonhosted.org/packages/46/03/07c4894aae38b0de52b52586b24bf189bb83e4ddabfe2e2c8f2419eec6f4/idna-ssl-1.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/46/03/07c4894aae38b0de52b52586b24bf189bb83e4ddabfe2e2c8f2419eec6f4/idna-ssl-1.1.0.tar.gz
Summary  : Patch ssl.match_hostname for Unicode(idna) domains support
Group    : Development/Tools
License  : MIT
Requires: idna-ssl-license = %{version}-%{release}
Requires: idna-ssl-python = %{version}-%{release}
Requires: idna-ssl-python3 = %{version}-%{release}
Requires: idna
BuildRequires : buildreq-distutils3
BuildRequires : idna
BuildRequires : pytest-runner

%description
idna-ssl
========

:info: Patch ssl.match_hostname for Unicode(idna) domains support

.. image:: https://travis-ci.com/aio-libs/idna-ssl.svg?branch=master
    :target: https://travis-ci.com/aio-libs/idna-ssl

.. image:: https://img.shields.io/pypi/v/idna_ssl.svg
    :target: https://pypi.python.org/pypi/idna_ssl

.. image:: https://codecov.io/gh/aio-libs/idna-ssl/branch/master/graph/badge.svg
    :target: https://codecov.io/gh/aio-libs/idna-ssl

Installation
------------

.. code-block:: shell

    pip install idna-ssl

Usage
-----

.. code-block:: python

    from idna_ssl import patch_match_hostname  # noqa isort:skip
    patch_match_hostname()  # noqa isort:skip

    import asyncio

    import aiohttp

    URL = 'https://цфоут.мвд.рф/news/item/8065038/'


    async def main():
        async with aiohttp.ClientSession() as session:
            async with session.get(URL) as response:
                print(response)


    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())

Motivation
----------

* Here is 100% backward capability
* Related aiohttp `issue <https://github.com/aio-libs/aiohttp/issues/949>`_
* Related Python `bug <https://bugs.python.org/issue31872>`_
* Related Python `pull request <https://github.com/python/cpython/pull/3462>`_
* It is fixed (by January 27 2018) in upcoming Python 3.7, but `IDNA2008 <https://tools.ietf.org/html/rfc5895>`_ is still broken

Thanks
------

The library was donated by `Ocean S.A. <https://ocean.io/>`_

Thanks to the company for contribution.

%package license
Summary: license components for the idna-ssl package.
Group: Default

%description license
license components for the idna-ssl package.


%package python
Summary: python components for the idna-ssl package.
Group: Default
Requires: idna-ssl-python3 = %{version}-%{release}

%description python
python components for the idna-ssl package.


%package python3
Summary: python3 components for the idna-ssl package.
Group: Default
Requires: python3-core
Provides: pypi(idna_ssl)

%description python3
python3 components for the idna-ssl package.


%prep
%setup -q -n idna-ssl-1.1.0
cd %{_builddir}/idna-ssl-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582937158
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/idna-ssl
cp %{_builddir}/idna-ssl-1.1.0/LICENSE %{buildroot}/usr/share/package-licenses/idna-ssl/6b8689c0fd8786e0c546e954329ce66432f51dc1
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/idna-ssl/6b8689c0fd8786e0c546e954329ce66432f51dc1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
